### ISSUE TITLE
False temperature reading with librasp on DS18B20

### ISSUE THREAD

**Issue by martinlwtzky** [pstolarz/librasp#1] opened 2016-02-15 11:53 UTC
Thank you for sharing your great library for Raspberry Pi!

Trying to read the temperature off a DS18B20, I'm having the following issue:
Reading the temperature through /dev interface is giving me:
`cat //sys/bus/w1/devices/28-000006c5aefc/w1_slave`
`4b 01 4b 46 7f ff 05 10 e1 : crc=e1 YES`
`4b 01 4b 46 7f ff 05 10 e1 t=20687`

librasp is also seeing that sensor:
`./dsth_list2`
`w1 master [0x00000001]`
 `DS18B20 [0xe9000006c5aefc28]; T:85.0`

However, the temperature reading is different (wrong) in librasp reading. The true temperature is about 20,687°C as indicated in the /dev reading. 

Do you have any idea what I might be doing wrong?

```
./dsth_list
Feb 15 12:52:41 DEBUG: [NLSCK:3]: -> netlink [header]: len:0x00000030 type:0x0003 flags:0x0000 seq:0x00000000 pid:0x00000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000000 ack:0xffffffff len:0x000c flags:0x0000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x06 status:0x00 len:0x0000 id:0x00000000|0x00000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000034 type:0x0003 flags:0x0000 seq:0x00000000 pid:0x00000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000000 ack:0x00000001 len:0x0010 flags:0x6269
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x06 status:0x00 len:0x0004 id:0x6e696c2d|0x672d7875 data[hex bts]:01000000
w1 master [0x00000001]
Feb 15 12:52:41 DEBUG: [NLSCK:3]: -> netlink [header]: len:0x00000034 type:0x0003 flags:0x0000 seq:0x00000001 pid:0x00000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000001 ack:0xffffffff len:0x0010 flags:0x0000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x04 status:0x00 len:0x0004 id:0x00000001|0x00000000 data[hex bts]:02000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x0000003c type:0x0003 flags:0x0000 seq:0x00000001 pid:0x00000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000001 ack:0x00000002 len:0x0018 flags:0x0000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x04 status:0x00 len:0x000c id:0x00000001|0x00000000 data[hex bts]:0200080028fcaec5060000e9
Feb 15 12:52:41 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000034 type:0x0003 flags:0x0000 seq:0x00000001 pid:0x00000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000001 ack:0xffffffff len:0x0010 flags:0x0000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x04 status:0x00 len:0x0004 id:0x00000001|0x00000000 data[hex bts]:02000000
 DS18B20 [0xe9000006c5aefc28]; T:Feb 15 12:52:41 DEBUG: [NLSCK:3]: -> netlink [header]: len:0x0000003e type:0x0003 flags:0x0000 seq:0x00000002 pid:0x00000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000002 ack:0xffffffff len:0x001a flags:0x0000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x000e id:0xc5aefc28|0xe9000006 data[hex bts]:04000a00beffffffffffffffffff
Feb 15 12:52:41 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000024 type:0x0003 flags:0x0000 seq:0x00000000 pid:0x00000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000000|0x00000000 seq:0x00000000 ack:0x00000000 len:0x0000 flags:0x0000; filtered out: no w1 msg
Feb 15 12:52:41 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x0000003e type:0x0003 flags:0x0000 seq:0x00000002 pid:0x00000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000002 ack:0x00000003 len:0x001a flags:0x0000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x000e id:0xc5aefc28|0xe9000006 data[hex bts]:04000a00be50054b467fff0c101c
Feb 15 12:52:41 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000034 type:0x0003 flags:0x0000 seq:0x00000002 pid:0x00000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000002 ack:0xffffffff len:0x0010 flags:0x0000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x0004 id:0xc5aefc28|0xe9000006 data[hex bts]:04000000
Feb 15 12:52:41 DEBUG: [dsth_probe] DS therm resolution: 12-bit
Feb 15 12:52:41 DEBUG: [NLSCK:3]: -> netlink [header]: len:0x00000035 type:0x0003 flags:0x0000 seq:0x00000003 pid:0x00000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000003 ack:0xffffffff len:0x0011 flags:0x0000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x0005 id:0xc5aefc28|0xe9000006 data[hex bts]:0400010044
Feb 15 12:52:41 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000024 type:0x0003 flags:0x0000 seq:0x00000000 pid:0x00000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000000|0x00000000 seq:0x00000000 ack:0x00000000 len:0x0000 flags:0x0000; filtered out: no w1 msg
Feb 15 12:52:41 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000035 type:0x0003 flags:0x0000 seq:0x00000003 pid:0x00000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000003 ack:0x00000004 len:0x0011 flags:0x0000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x0005 id:0xc5aefc28|0xe9000006 data[hex bts]:0400010044
Feb 15 12:52:41 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000034 type:0x0003 flags:0x0000 seq:0x00000003 pid:0x00000000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000003 ack:0xffffffff len:0x0010 flags:0x0000
Feb 15 12:52:41 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x0004 id:0xc5aefc28|0xe9000006 data[hex bts]:04000000
Feb 15 12:52:42 DEBUG: [NLSCK:3]: -> netlink [header]: len:0x0000003e type:0x0003 flags:0x0000 seq:0x00000004 pid:0x00000000
Feb 15 12:52:42 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000004 ack:0xffffffff len:0x001a flags:0x0000
Feb 15 12:52:42 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x000e id:0xc5aefc28|0xe9000006 data[hex bts]:04000a00beffffffffffffffffff
Feb 15 12:52:42 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000024 type:0x0003 flags:0x0000 seq:0x00000000 pid:0x00000000
Feb 15 12:52:42 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000000|0x00000000 seq:0x00000000 ack:0x00000000 len:0x0000 flags:0x0000; filtered out: no w1 msg
Feb 15 12:52:42 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x0000003e type:0x0003 flags:0x0000 seq:0x00000004 pid:0x00000000
Feb 15 12:52:42 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000004 ack:0x00000005 len:0x001a flags:0x0000
Feb 15 12:52:42 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x000e id:0xc5aefc28|0xe9000006 data[hex bts]:04000a00be50054b467fff0c101c
Feb 15 12:52:42 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000034 type:0x0003 flags:0x0000 seq:0x00000004 pid:0x00000000
Feb 15 12:52:42 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000004 ack:0xffffffff len:0x0010 flags:0x0000
Feb 15 12:52:42 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x0004 id:0xc5aefc28|0xe9000006 data[hex bts]:04000000
Feb 15 12:52:42 DEBUG: [dsth_probe] temp-lsb:0x50, temp-hsb:0x05
85.0

```

Thank you very much in advance!

Martin

**Comment by pstolarz** [comment] 2016-02-15 14:51
I guess, you have other w1 driver (eg "w1_therm", or you use other type of w1 stuff like OWFS) interfering on the w1 bus. Unload any w1 modules except w1_gpio and let me know about results. BTW what kernel ver do you use?

**Comment by martinlwtzky** [comment] 2016-02-15 15:09
Dear Piotr, 
thank you vor your quick reply!
My Kernel version is "Linux raspberrypi 4.1.17+ #834 Mon Feb 1 15:13:47 GMT 2016 armv6l GNU/Linux"

I tried unloading w1_therm (rmmod)

```
lsmod
Module                  Size  Used by
cfg80211              477515  0 
rfkill                 21439  1 cfg80211
i2c_dev                 6406  0 
fb_st7735r              3916  1 
fbtft_device           35066  0 
fbtft                  34064  2 fb_st7735r,fbtft_device
syscopyarea             3113  1 fbtft
sysfillrect             3592  1 fbtft
sysimgblt               2286  1 fbtft
fb_sys_fops             1573  1 fbtft
snd_bcm2835            22317  0 
snd_pcm                92397  1 snd_bcm2835
snd_seq                57837  0 
snd_seq_device          5130  1 snd_seq
snd_timer              21932  2 snd_pcm,snd_seq
snd                    66988  5 snd_bcm2835,snd_timer,snd_pcm,snd_seq,snd_seq_device
cp210x                  9027  0 
8192cu                567860  0 
usbserial              29640  1 cp210x
i2c_bcm2708             6068  0 
bcm2835_rng             2215  0 
bcm2835_gpiomem         3703  0 
spi_bcm2835             7948  0 
w1_gpio                 4295  0 
wire                   30931  1 w1_gpio
cn                      5756  1 wire
uio_pdrv_genirq         3550  0 
uio                    10002  1 uio_pdrv_genirq
```

The result, however, did not change:

```
/dsth_list
Feb 15 15:54:13 DEBUG: [NLSCK:3]: -> netlink [header]: len:0x00000030 type:0x0003 flags:0x0000 seq:0x00000000 pid:0x00000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000000 ack:0xffffffff len:0x000c flags:0x0000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x06 status:0x00 len:0x0000 id:0x00000000|0x00000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000034 type:0x0003 flags:0x0000 seq:0x00000000 pid:0x00000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000000 ack:0x00000001 len:0x0010 flags:0x6269
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x06 status:0x00 len:0x0004 id:0x6e696c2d|0x672d7875 data[hex bts]:01000000
w1 master [0x00000001]
Feb 15 15:54:13 DEBUG: [NLSCK:3]: -> netlink [header]: len:0x00000034 type:0x0003 flags:0x0000 seq:0x00000001 pid:0x00000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000001 ack:0xffffffff len:0x0010 flags:0x0000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x04 status:0x00 len:0x0004 id:0x00000001|0x00000000 data[hex bts]:02000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x0000003c type:0x0003 flags:0x0000 seq:0x00000001 pid:0x00000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000001 ack:0x00000002 len:0x0018 flags:0x0000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x04 status:0x00 len:0x000c id:0x00000001|0x00000000 data[hex bts]:0200080028fcaec5060000e9
Feb 15 15:54:13 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000034 type:0x0003 flags:0x0000 seq:0x00000001 pid:0x00000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000001 ack:0xffffffff len:0x0010 flags:0x0000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x04 status:0x00 len:0x0004 id:0x00000001|0x00000000 data[hex bts]:02000000
 DS18B20 [0xe9000006c5aefc28]; T:Feb 15 15:54:13 DEBUG: [NLSCK:3]: -> netlink [header]: len:0x0000003e type:0x0003 flags:0x0000 seq:0x00000002 pid:0x00000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000002 ack:0xffffffff len:0x001a flags:0x0000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x000e id:0xc5aefc28|0xe9000006 data[hex bts]:04000a00beffffffffffffffffff
Feb 15 15:54:13 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000024 type:0x0003 flags:0x0000 seq:0x00000000 pid:0x00000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000000|0x00000000 seq:0x00000000 ack:0x00000000 len:0x0000 flags:0x0000; filtered out: no w1 msg
Feb 15 15:54:13 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x0000003e type:0x0003 flags:0x0000 seq:0x00000002 pid:0x00000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000002 ack:0x00000003 len:0x001a flags:0x0000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x000e id:0xc5aefc28|0xe9000006 data[hex bts]:04000a00be50054b467fff0c101c
Feb 15 15:54:13 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000034 type:0x0003 flags:0x0000 seq:0x00000002 pid:0x00000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000002 ack:0xffffffff len:0x0010 flags:0x0000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x0004 id:0xc5aefc28|0xe9000006 data[hex bts]:04000000
Feb 15 15:54:13 DEBUG: [dsth_probe] DS therm resolution: 12-bit
Feb 15 15:54:13 DEBUG: [NLSCK:3]: -> netlink [header]: len:0x00000035 type:0x0003 flags:0x0000 seq:0x00000003 pid:0x00000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000003 ack:0xffffffff len:0x0011 flags:0x0000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x0005 id:0xc5aefc28|0xe9000006 data[hex bts]:0400010044
Feb 15 15:54:13 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000024 type:0x0003 flags:0x0000 seq:0x00000000 pid:0x00000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000000|0x00000000 seq:0x00000000 ack:0x00000000 len:0x0000 flags:0x0000; filtered out: no w1 msg
Feb 15 15:54:13 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000035 type:0x0003 flags:0x0000 seq:0x00000003 pid:0x00000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000003 ack:0x00000004 len:0x0011 flags:0x0000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x0005 id:0xc5aefc28|0xe9000006 data[hex bts]:0400010044
Feb 15 15:54:13 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000034 type:0x0003 flags:0x0000 seq:0x00000003 pid:0x00000000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000003 ack:0xffffffff len:0x0010 flags:0x0000
Feb 15 15:54:13 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x0004 id:0xc5aefc28|0xe9000006 data[hex bts]:04000000
Feb 15 15:54:14 DEBUG: [NLSCK:3]: -> netlink [header]: len:0x0000003e type:0x0003 flags:0x0000 seq:0x00000004 pid:0x00000000
Feb 15 15:54:14 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000004 ack:0xffffffff len:0x001a flags:0x0000
Feb 15 15:54:14 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x000e id:0xc5aefc28|0xe9000006 data[hex bts]:04000a00beffffffffffffffffff
Feb 15 15:54:14 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000024 type:0x0003 flags:0x0000 seq:0x00000000 pid:0x00000000
Feb 15 15:54:14 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000000|0x00000000 seq:0x00000000 ack:0x00000000 len:0x0000 flags:0x0000; filtered out: no w1 msg
Feb 15 15:54:14 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x0000003e type:0x0003 flags:0x0000 seq:0x00000004 pid:0x00000000
Feb 15 15:54:14 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000004 ack:0x00000005 len:0x001a flags:0x0000
Feb 15 15:54:14 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x000e id:0xc5aefc28|0xe9000006 data[hex bts]:04000a00be50054b467fff0c101c
Feb 15 15:54:14 DEBUG: [NLSCK:3]: <- netlink [header]: len:0x00000034 type:0x0003 flags:0x0000 seq:0x00000004 pid:0x00000000
Feb 15 15:54:14 DEBUG: [NLSCK:3]:    nest. cn_msg [header]: id:0x00000003|0x00000001 seq:0x00000004 ack:0xffffffff len:0x0010 flags:0x0000
Feb 15 15:54:14 DEBUG: [NLSCK:3]:    nest. w1_msg [header]: type:0x05 status:0x00 len:0x0004 id:0xc5aefc28|0xe9000006 data[hex bts]:04000000
Feb 15 15:54:14 DEBUG: [dsth_probe] temp-lsb:0x50, temp-hsb:0x05
85.0
```

I am currently patching my Kernel with your patch (w1_netlink). I will let you know if that changes the result!

Thank you very much!

Martin

**Comment by pstolarz** [comment] 2016-02-15 17:55
Hi Martin,
The patch wont help you here. The problem you have is something strange. 85 C is the initial value of the temperature field in the sensor's scratchpad (see https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf page 6, table 1). It looks like the sensors is powered off between Convert T (0x44) and Read Scratchpad (0xBE) commands.
I'll need to try do the test on the same version of kernel as yours.

**Comment by martinlwtzky** [comment] 2016-02-15 20:18
Dear Piotr,

thank you very much for sharing your insight on this! If there is anything I can do to debug this issue, please let me know! Not sure if this is of any importance: I connected the DS18B20 in parasite power configuration, Vdd to GND and signal line pulled up to +3.3V through 4.7k as suggested [here](http://www.tweaking4all.com/wp-content/uploads/2014/03/ds18b20-parasite-power.jpg). This works fine using the /dev interface, so I assume there is some software issue.

Thank you very much for your help!

Martin

**Comment by pstolarz** [comment] 2016-02-15 21:22
Yes, the problem is associated with the parasite powering of the sensor. Try to connect the sensor in the non-parasite mode and everything should work fine.

The reason why your sensor works with sysfs driver (w1_therm) and doesn't work via w1-netlink (which librasp uses under the hood) is, the kernel w1 author doesn't provide proper way to handle parasite powering via the netlink interface. Specifically, parasiting mode need an extra period of time between the Convert T and Read Scratchpad commands, where direct voltage source need to be provided on the w1 bus. This functionality is absent in the w1 netlink intf. To handle this issue I tried to patch the interface (by adding an extra W1_CMD_WRITE_PULLUP netlink command) but didn't get satisfactory results (due to some other problems in "w1_gpio" - gpio w1 master). Since parasite powering was not so important for me I aborted further work on this issue.
If the parasite powering is a must-have feature for you I may try to work on this topic more thoroughly but dont promise I'll do it soon.

w1_therm works fine in the parasitic power since it is properly handled in the w1_therm (see kernel's drivers/w1/slaves/w1_therm.c -> w1_slave_show() where an  extra pullup duration is provided via w1_next_pullup() call if parasitic mode is detected). You can't request such pullup via netlink intf.

**Comment by martinlwtzky** [comment] 2016-02-15 21:38
Dear Piotr,
thank you very much for the information! Parasite power is actually a must for my application. However, I can stick to parsing the /dev interface as long as librasp does not support that mode. I might also give it a shot and try to activate the pullup during that extra period. If I find any solution, I'll be happy to share it!

Cheers
Martin

**Comment by pstolarz** [comment] 2016-02-15 22:05
So, try to patch the kernel with my netlink patch (resolving possible conflicts for new 4.1.x kernel, since my patch is for the 3.18 one). Next compile the library with CONFIG_WRITE_PULLUP (simply edit the config.h file).

Finally activate w1 in the parasitic mode via proper overlay. Look at /boot/overlays/README for more info about w1-gpio and w1-gpio-pullup (if you need an external pull up). I'll also need to look at new kernel 4.1.x w1-gpio code, since I see lot of changes since 3.x branch.

Piotrek

**Comment by pstolarz** [comment] 2016-04-05 10:00
Hi Martin,
I provided some changes for parasite powering of DS temp. sensors support. Verified it on 4.1.19 kernel (patched) and looking good. If you are still interested in using the lib with parasite powering check it out. I've updated README files with more info.

Piotrek

**Closed as completed** 2016-04-16 08:03 UTC
Labels: enhancement
